// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NavigationChallenge.proto

package org.robocup_logistics.llsf_msgs;

public final class NavigationChallengeProtos {
  private NavigationChallengeProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RouteOrBuilder extends
      // @@protoc_insertion_point(interface_extends:llsf_msgs.Route)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required uint32 id = 1;</code>
     */
    int getId();

    /**
     * <code>repeated .llsf_msgs.Zone route = 2;</code>
     */
    java.util.List<org.robocup_logistics.llsf_msgs.ZoneProtos.Zone> getRouteList();
    /**
     * <code>repeated .llsf_msgs.Zone route = 2;</code>
     */
    int getRouteCount();
    /**
     * <code>repeated .llsf_msgs.Zone route = 2;</code>
     */
    org.robocup_logistics.llsf_msgs.ZoneProtos.Zone getRoute(int index);

    /**
     * <code>repeated .llsf_msgs.Zone reached = 3;</code>
     */
    java.util.List<org.robocup_logistics.llsf_msgs.ZoneProtos.Zone> getReachedList();
    /**
     * <code>repeated .llsf_msgs.Zone reached = 3;</code>
     */
    int getReachedCount();
    /**
     * <code>repeated .llsf_msgs.Zone reached = 3;</code>
     */
    org.robocup_logistics.llsf_msgs.ZoneProtos.Zone getReached(int index);

    /**
     * <code>repeated .llsf_msgs.Zone remaining = 4;</code>
     */
    java.util.List<org.robocup_logistics.llsf_msgs.ZoneProtos.Zone> getRemainingList();
    /**
     * <code>repeated .llsf_msgs.Zone remaining = 4;</code>
     */
    int getRemainingCount();
    /**
     * <code>repeated .llsf_msgs.Zone remaining = 4;</code>
     */
    org.robocup_logistics.llsf_msgs.ZoneProtos.Zone getRemaining(int index);
  }
  /**
   * Protobuf type {@code llsf_msgs.Route}
   */
  public static final class Route extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:llsf_msgs.Route)
      RouteOrBuilder {
    // Use Route.newBuilder() to construct.
    private Route(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Route(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Route defaultInstance;
    public static Route getDefaultInstance() {
      return defaultInstance;
    }

    public Route getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Route(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readUInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              org.robocup_logistics.llsf_msgs.ZoneProtos.Zone value = org.robocup_logistics.llsf_msgs.ZoneProtos.Zone.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
                } else {
                if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                  route_ = new java.util.ArrayList<org.robocup_logistics.llsf_msgs.ZoneProtos.Zone>();
                  mutable_bitField0_ |= 0x00000002;
                }
                route_.add(value);
              }
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int oldLimit = input.pushLimit(length);
              while(input.getBytesUntilLimit() > 0) {
                int rawValue = input.readEnum();
                org.robocup_logistics.llsf_msgs.ZoneProtos.Zone value = org.robocup_logistics.llsf_msgs.ZoneProtos.Zone.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(2, rawValue);
                  } else {
                  if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                    route_ = new java.util.ArrayList<org.robocup_logistics.llsf_msgs.ZoneProtos.Zone>();
                    mutable_bitField0_ |= 0x00000002;
                  }
                  route_.add(value);
                }
              }
              input.popLimit(oldLimit);
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              org.robocup_logistics.llsf_msgs.ZoneProtos.Zone value = org.robocup_logistics.llsf_msgs.ZoneProtos.Zone.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
                } else {
                if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                  reached_ = new java.util.ArrayList<org.robocup_logistics.llsf_msgs.ZoneProtos.Zone>();
                  mutable_bitField0_ |= 0x00000004;
                }
                reached_.add(value);
              }
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int oldLimit = input.pushLimit(length);
              while(input.getBytesUntilLimit() > 0) {
                int rawValue = input.readEnum();
                org.robocup_logistics.llsf_msgs.ZoneProtos.Zone value = org.robocup_logistics.llsf_msgs.ZoneProtos.Zone.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(3, rawValue);
                  } else {
                  if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                    reached_ = new java.util.ArrayList<org.robocup_logistics.llsf_msgs.ZoneProtos.Zone>();
                    mutable_bitField0_ |= 0x00000004;
                  }
                  reached_.add(value);
                }
              }
              input.popLimit(oldLimit);
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              org.robocup_logistics.llsf_msgs.ZoneProtos.Zone value = org.robocup_logistics.llsf_msgs.ZoneProtos.Zone.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
                } else {
                if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                  remaining_ = new java.util.ArrayList<org.robocup_logistics.llsf_msgs.ZoneProtos.Zone>();
                  mutable_bitField0_ |= 0x00000008;
                }
                remaining_.add(value);
              }
              break;
            }
            case 34: {
              int length = input.readRawVarint32();
              int oldLimit = input.pushLimit(length);
              while(input.getBytesUntilLimit() > 0) {
                int rawValue = input.readEnum();
                org.robocup_logistics.llsf_msgs.ZoneProtos.Zone value = org.robocup_logistics.llsf_msgs.ZoneProtos.Zone.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(4, rawValue);
                  } else {
                  if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                    remaining_ = new java.util.ArrayList<org.robocup_logistics.llsf_msgs.ZoneProtos.Zone>();
                    mutable_bitField0_ |= 0x00000008;
                  }
                  remaining_.add(value);
                }
              }
              input.popLimit(oldLimit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          route_ = java.util.Collections.unmodifiableList(route_);
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          reached_ = java.util.Collections.unmodifiableList(reached_);
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          remaining_ = java.util.Collections.unmodifiableList(remaining_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.internal_static_llsf_msgs_Route_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.internal_static_llsf_msgs_Route_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.Route.class, org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.Route.Builder.class);
    }

    public static com.google.protobuf.Parser<Route> PARSER =
        new com.google.protobuf.AbstractParser<Route>() {
      public Route parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Route(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Route> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required uint32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int ROUTE_FIELD_NUMBER = 2;
    private java.util.List<org.robocup_logistics.llsf_msgs.ZoneProtos.Zone> route_;
    /**
     * <code>repeated .llsf_msgs.Zone route = 2;</code>
     */
    public java.util.List<org.robocup_logistics.llsf_msgs.ZoneProtos.Zone> getRouteList() {
      return route_;
    }
    /**
     * <code>repeated .llsf_msgs.Zone route = 2;</code>
     */
    public int getRouteCount() {
      return route_.size();
    }
    /**
     * <code>repeated .llsf_msgs.Zone route = 2;</code>
     */
    public org.robocup_logistics.llsf_msgs.ZoneProtos.Zone getRoute(int index) {
      return route_.get(index);
    }

    public static final int REACHED_FIELD_NUMBER = 3;
    private java.util.List<org.robocup_logistics.llsf_msgs.ZoneProtos.Zone> reached_;
    /**
     * <code>repeated .llsf_msgs.Zone reached = 3;</code>
     */
    public java.util.List<org.robocup_logistics.llsf_msgs.ZoneProtos.Zone> getReachedList() {
      return reached_;
    }
    /**
     * <code>repeated .llsf_msgs.Zone reached = 3;</code>
     */
    public int getReachedCount() {
      return reached_.size();
    }
    /**
     * <code>repeated .llsf_msgs.Zone reached = 3;</code>
     */
    public org.robocup_logistics.llsf_msgs.ZoneProtos.Zone getReached(int index) {
      return reached_.get(index);
    }

    public static final int REMAINING_FIELD_NUMBER = 4;
    private java.util.List<org.robocup_logistics.llsf_msgs.ZoneProtos.Zone> remaining_;
    /**
     * <code>repeated .llsf_msgs.Zone remaining = 4;</code>
     */
    public java.util.List<org.robocup_logistics.llsf_msgs.ZoneProtos.Zone> getRemainingList() {
      return remaining_;
    }
    /**
     * <code>repeated .llsf_msgs.Zone remaining = 4;</code>
     */
    public int getRemainingCount() {
      return remaining_.size();
    }
    /**
     * <code>repeated .llsf_msgs.Zone remaining = 4;</code>
     */
    public org.robocup_logistics.llsf_msgs.ZoneProtos.Zone getRemaining(int index) {
      return remaining_.get(index);
    }

    private void initFields() {
      id_ = 0;
      route_ = java.util.Collections.emptyList();
      reached_ = java.util.Collections.emptyList();
      remaining_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, id_);
      }
      for (int i = 0; i < route_.size(); i++) {
        output.writeEnum(2, route_.get(i).getNumber());
      }
      for (int i = 0; i < reached_.size(); i++) {
        output.writeEnum(3, reached_.get(i).getNumber());
      }
      for (int i = 0; i < remaining_.size(); i++) {
        output.writeEnum(4, remaining_.get(i).getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, id_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < route_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeEnumSizeNoTag(route_.get(i).getNumber());
        }
        size += dataSize;
        size += 1 * route_.size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < reached_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeEnumSizeNoTag(reached_.get(i).getNumber());
        }
        size += dataSize;
        size += 1 * reached_.size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < remaining_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeEnumSizeNoTag(remaining_.get(i).getNumber());
        }
        size += dataSize;
        size += 1 * remaining_.size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.Route parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.Route parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.Route parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.Route parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.Route parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.Route parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.Route parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.Route parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.Route parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.Route parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.Route prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code llsf_msgs.Route}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:llsf_msgs.Route)
        org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.RouteOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.internal_static_llsf_msgs_Route_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.internal_static_llsf_msgs_Route_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.Route.class, org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.Route.Builder.class);
      }

      // Construct using org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.Route.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        route_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        reached_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        remaining_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.internal_static_llsf_msgs_Route_descriptor;
      }

      public org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.Route getDefaultInstanceForType() {
        return org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.Route.getDefaultInstance();
      }

      public org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.Route build() {
        org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.Route result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.Route buildPartial() {
        org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.Route result = new org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.Route(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          route_ = java.util.Collections.unmodifiableList(route_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.route_ = route_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          reached_ = java.util.Collections.unmodifiableList(reached_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.reached_ = reached_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          remaining_ = java.util.Collections.unmodifiableList(remaining_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.remaining_ = remaining_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.Route) {
          return mergeFrom((org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.Route)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.Route other) {
        if (other == org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.Route.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (!other.route_.isEmpty()) {
          if (route_.isEmpty()) {
            route_ = other.route_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureRouteIsMutable();
            route_.addAll(other.route_);
          }
          onChanged();
        }
        if (!other.reached_.isEmpty()) {
          if (reached_.isEmpty()) {
            reached_ = other.reached_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureReachedIsMutable();
            reached_.addAll(other.reached_);
          }
          onChanged();
        }
        if (!other.remaining_.isEmpty()) {
          if (remaining_.isEmpty()) {
            remaining_ = other.remaining_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureRemainingIsMutable();
            remaining_.addAll(other.remaining_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.Route parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.Route) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required uint32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required uint32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<org.robocup_logistics.llsf_msgs.ZoneProtos.Zone> route_ =
        java.util.Collections.emptyList();
      private void ensureRouteIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          route_ = new java.util.ArrayList<org.robocup_logistics.llsf_msgs.ZoneProtos.Zone>(route_);
          bitField0_ |= 0x00000002;
        }
      }
      /**
       * <code>repeated .llsf_msgs.Zone route = 2;</code>
       */
      public java.util.List<org.robocup_logistics.llsf_msgs.ZoneProtos.Zone> getRouteList() {
        return java.util.Collections.unmodifiableList(route_);
      }
      /**
       * <code>repeated .llsf_msgs.Zone route = 2;</code>
       */
      public int getRouteCount() {
        return route_.size();
      }
      /**
       * <code>repeated .llsf_msgs.Zone route = 2;</code>
       */
      public org.robocup_logistics.llsf_msgs.ZoneProtos.Zone getRoute(int index) {
        return route_.get(index);
      }
      /**
       * <code>repeated .llsf_msgs.Zone route = 2;</code>
       */
      public Builder setRoute(
          int index, org.robocup_logistics.llsf_msgs.ZoneProtos.Zone value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRouteIsMutable();
        route_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .llsf_msgs.Zone route = 2;</code>
       */
      public Builder addRoute(org.robocup_logistics.llsf_msgs.ZoneProtos.Zone value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRouteIsMutable();
        route_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .llsf_msgs.Zone route = 2;</code>
       */
      public Builder addAllRoute(
          java.lang.Iterable<? extends org.robocup_logistics.llsf_msgs.ZoneProtos.Zone> values) {
        ensureRouteIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, route_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .llsf_msgs.Zone route = 2;</code>
       */
      public Builder clearRoute() {
        route_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      private java.util.List<org.robocup_logistics.llsf_msgs.ZoneProtos.Zone> reached_ =
        java.util.Collections.emptyList();
      private void ensureReachedIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          reached_ = new java.util.ArrayList<org.robocup_logistics.llsf_msgs.ZoneProtos.Zone>(reached_);
          bitField0_ |= 0x00000004;
        }
      }
      /**
       * <code>repeated .llsf_msgs.Zone reached = 3;</code>
       */
      public java.util.List<org.robocup_logistics.llsf_msgs.ZoneProtos.Zone> getReachedList() {
        return java.util.Collections.unmodifiableList(reached_);
      }
      /**
       * <code>repeated .llsf_msgs.Zone reached = 3;</code>
       */
      public int getReachedCount() {
        return reached_.size();
      }
      /**
       * <code>repeated .llsf_msgs.Zone reached = 3;</code>
       */
      public org.robocup_logistics.llsf_msgs.ZoneProtos.Zone getReached(int index) {
        return reached_.get(index);
      }
      /**
       * <code>repeated .llsf_msgs.Zone reached = 3;</code>
       */
      public Builder setReached(
          int index, org.robocup_logistics.llsf_msgs.ZoneProtos.Zone value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureReachedIsMutable();
        reached_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .llsf_msgs.Zone reached = 3;</code>
       */
      public Builder addReached(org.robocup_logistics.llsf_msgs.ZoneProtos.Zone value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureReachedIsMutable();
        reached_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .llsf_msgs.Zone reached = 3;</code>
       */
      public Builder addAllReached(
          java.lang.Iterable<? extends org.robocup_logistics.llsf_msgs.ZoneProtos.Zone> values) {
        ensureReachedIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, reached_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .llsf_msgs.Zone reached = 3;</code>
       */
      public Builder clearReached() {
        reached_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      private java.util.List<org.robocup_logistics.llsf_msgs.ZoneProtos.Zone> remaining_ =
        java.util.Collections.emptyList();
      private void ensureRemainingIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          remaining_ = new java.util.ArrayList<org.robocup_logistics.llsf_msgs.ZoneProtos.Zone>(remaining_);
          bitField0_ |= 0x00000008;
        }
      }
      /**
       * <code>repeated .llsf_msgs.Zone remaining = 4;</code>
       */
      public java.util.List<org.robocup_logistics.llsf_msgs.ZoneProtos.Zone> getRemainingList() {
        return java.util.Collections.unmodifiableList(remaining_);
      }
      /**
       * <code>repeated .llsf_msgs.Zone remaining = 4;</code>
       */
      public int getRemainingCount() {
        return remaining_.size();
      }
      /**
       * <code>repeated .llsf_msgs.Zone remaining = 4;</code>
       */
      public org.robocup_logistics.llsf_msgs.ZoneProtos.Zone getRemaining(int index) {
        return remaining_.get(index);
      }
      /**
       * <code>repeated .llsf_msgs.Zone remaining = 4;</code>
       */
      public Builder setRemaining(
          int index, org.robocup_logistics.llsf_msgs.ZoneProtos.Zone value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRemainingIsMutable();
        remaining_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .llsf_msgs.Zone remaining = 4;</code>
       */
      public Builder addRemaining(org.robocup_logistics.llsf_msgs.ZoneProtos.Zone value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRemainingIsMutable();
        remaining_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .llsf_msgs.Zone remaining = 4;</code>
       */
      public Builder addAllRemaining(
          java.lang.Iterable<? extends org.robocup_logistics.llsf_msgs.ZoneProtos.Zone> values) {
        ensureRemainingIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, remaining_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .llsf_msgs.Zone remaining = 4;</code>
       */
      public Builder clearRemaining() {
        remaining_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:llsf_msgs.Route)
    }

    static {
      defaultInstance = new Route(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:llsf_msgs.Route)
  }

  public interface NavigationRoutesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:llsf_msgs.NavigationRoutes)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .llsf_msgs.Team team_color = 1;</code>
     */
    boolean hasTeamColor();
    /**
     * <code>required .llsf_msgs.Team team_color = 1;</code>
     */
    org.robocup_logistics.llsf_msgs.TeamProtos.Team getTeamColor();

    /**
     * <code>repeated .llsf_msgs.Route routes = 5;</code>
     */
    java.util.List<org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.Route> 
        getRoutesList();
    /**
     * <code>repeated .llsf_msgs.Route routes = 5;</code>
     */
    org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.Route getRoutes(int index);
    /**
     * <code>repeated .llsf_msgs.Route routes = 5;</code>
     */
    int getRoutesCount();
    /**
     * <code>repeated .llsf_msgs.Route routes = 5;</code>
     */
    java.util.List<? extends org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.RouteOrBuilder> 
        getRoutesOrBuilderList();
    /**
     * <code>repeated .llsf_msgs.Route routes = 5;</code>
     */
    org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.RouteOrBuilder getRoutesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code llsf_msgs.NavigationRoutes}
   */
  public static final class NavigationRoutes extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:llsf_msgs.NavigationRoutes)
      NavigationRoutesOrBuilder {
    // Use NavigationRoutes.newBuilder() to construct.
    private NavigationRoutes(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private NavigationRoutes(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final NavigationRoutes defaultInstance;
    public static NavigationRoutes getDefaultInstance() {
      return defaultInstance;
    }

    public NavigationRoutes getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private NavigationRoutes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              org.robocup_logistics.llsf_msgs.TeamProtos.Team value = org.robocup_logistics.llsf_msgs.TeamProtos.Team.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                teamColor_ = value;
              }
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                routes_ = new java.util.ArrayList<org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.Route>();
                mutable_bitField0_ |= 0x00000002;
              }
              routes_.add(input.readMessage(org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.Route.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          routes_ = java.util.Collections.unmodifiableList(routes_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.internal_static_llsf_msgs_NavigationRoutes_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.internal_static_llsf_msgs_NavigationRoutes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.NavigationRoutes.class, org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.NavigationRoutes.Builder.class);
    }

    public static com.google.protobuf.Parser<NavigationRoutes> PARSER =
        new com.google.protobuf.AbstractParser<NavigationRoutes>() {
      public NavigationRoutes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NavigationRoutes(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<NavigationRoutes> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code llsf_msgs.NavigationRoutes.CompType}
     */
    public enum CompType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>COMP_ID = 2000;</code>
       */
      COMP_ID(0, 2000),
      /**
       * <code>MSG_TYPE = 250;</code>
       */
      MSG_TYPE(1, 250),
      ;

      /**
       * <code>COMP_ID = 2000;</code>
       */
      public static final int COMP_ID_VALUE = 2000;
      /**
       * <code>MSG_TYPE = 250;</code>
       */
      public static final int MSG_TYPE_VALUE = 250;


      public final int getNumber() { return value; }

      public static CompType valueOf(int value) {
        switch (value) {
          case 2000: return COMP_ID;
          case 250: return MSG_TYPE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<CompType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<CompType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CompType>() {
              public CompType findValueByNumber(int number) {
                return CompType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.NavigationRoutes.getDescriptor().getEnumTypes().get(0);
      }

      private static final CompType[] VALUES = values();

      public static CompType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private CompType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:llsf_msgs.NavigationRoutes.CompType)
    }

    private int bitField0_;
    public static final int TEAM_COLOR_FIELD_NUMBER = 1;
    private org.robocup_logistics.llsf_msgs.TeamProtos.Team teamColor_;
    /**
     * <code>required .llsf_msgs.Team team_color = 1;</code>
     */
    public boolean hasTeamColor() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .llsf_msgs.Team team_color = 1;</code>
     */
    public org.robocup_logistics.llsf_msgs.TeamProtos.Team getTeamColor() {
      return teamColor_;
    }

    public static final int ROUTES_FIELD_NUMBER = 5;
    private java.util.List<org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.Route> routes_;
    /**
     * <code>repeated .llsf_msgs.Route routes = 5;</code>
     */
    public java.util.List<org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.Route> getRoutesList() {
      return routes_;
    }
    /**
     * <code>repeated .llsf_msgs.Route routes = 5;</code>
     */
    public java.util.List<? extends org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.RouteOrBuilder> 
        getRoutesOrBuilderList() {
      return routes_;
    }
    /**
     * <code>repeated .llsf_msgs.Route routes = 5;</code>
     */
    public int getRoutesCount() {
      return routes_.size();
    }
    /**
     * <code>repeated .llsf_msgs.Route routes = 5;</code>
     */
    public org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.Route getRoutes(int index) {
      return routes_.get(index);
    }
    /**
     * <code>repeated .llsf_msgs.Route routes = 5;</code>
     */
    public org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.RouteOrBuilder getRoutesOrBuilder(
        int index) {
      return routes_.get(index);
    }

    private void initFields() {
      teamColor_ = org.robocup_logistics.llsf_msgs.TeamProtos.Team.CYAN;
      routes_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTeamColor()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getRoutesCount(); i++) {
        if (!getRoutes(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, teamColor_.getNumber());
      }
      for (int i = 0; i < routes_.size(); i++) {
        output.writeMessage(5, routes_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, teamColor_.getNumber());
      }
      for (int i = 0; i < routes_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, routes_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.NavigationRoutes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.NavigationRoutes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.NavigationRoutes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.NavigationRoutes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.NavigationRoutes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.NavigationRoutes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.NavigationRoutes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.NavigationRoutes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.NavigationRoutes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.NavigationRoutes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.NavigationRoutes prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code llsf_msgs.NavigationRoutes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:llsf_msgs.NavigationRoutes)
        org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.NavigationRoutesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.internal_static_llsf_msgs_NavigationRoutes_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.internal_static_llsf_msgs_NavigationRoutes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.NavigationRoutes.class, org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.NavigationRoutes.Builder.class);
      }

      // Construct using org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.NavigationRoutes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRoutesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        teamColor_ = org.robocup_logistics.llsf_msgs.TeamProtos.Team.CYAN;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (routesBuilder_ == null) {
          routes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          routesBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.internal_static_llsf_msgs_NavigationRoutes_descriptor;
      }

      public org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.NavigationRoutes getDefaultInstanceForType() {
        return org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.NavigationRoutes.getDefaultInstance();
      }

      public org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.NavigationRoutes build() {
        org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.NavigationRoutes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.NavigationRoutes buildPartial() {
        org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.NavigationRoutes result = new org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.NavigationRoutes(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.teamColor_ = teamColor_;
        if (routesBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            routes_ = java.util.Collections.unmodifiableList(routes_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.routes_ = routes_;
        } else {
          result.routes_ = routesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.NavigationRoutes) {
          return mergeFrom((org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.NavigationRoutes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.NavigationRoutes other) {
        if (other == org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.NavigationRoutes.getDefaultInstance()) return this;
        if (other.hasTeamColor()) {
          setTeamColor(other.getTeamColor());
        }
        if (routesBuilder_ == null) {
          if (!other.routes_.isEmpty()) {
            if (routes_.isEmpty()) {
              routes_ = other.routes_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureRoutesIsMutable();
              routes_.addAll(other.routes_);
            }
            onChanged();
          }
        } else {
          if (!other.routes_.isEmpty()) {
            if (routesBuilder_.isEmpty()) {
              routesBuilder_.dispose();
              routesBuilder_ = null;
              routes_ = other.routes_;
              bitField0_ = (bitField0_ & ~0x00000002);
              routesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getRoutesFieldBuilder() : null;
            } else {
              routesBuilder_.addAllMessages(other.routes_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTeamColor()) {
          
          return false;
        }
        for (int i = 0; i < getRoutesCount(); i++) {
          if (!getRoutes(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.NavigationRoutes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.NavigationRoutes) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private org.robocup_logistics.llsf_msgs.TeamProtos.Team teamColor_ = org.robocup_logistics.llsf_msgs.TeamProtos.Team.CYAN;
      /**
       * <code>required .llsf_msgs.Team team_color = 1;</code>
       */
      public boolean hasTeamColor() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .llsf_msgs.Team team_color = 1;</code>
       */
      public org.robocup_logistics.llsf_msgs.TeamProtos.Team getTeamColor() {
        return teamColor_;
      }
      /**
       * <code>required .llsf_msgs.Team team_color = 1;</code>
       */
      public Builder setTeamColor(org.robocup_logistics.llsf_msgs.TeamProtos.Team value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        teamColor_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .llsf_msgs.Team team_color = 1;</code>
       */
      public Builder clearTeamColor() {
        bitField0_ = (bitField0_ & ~0x00000001);
        teamColor_ = org.robocup_logistics.llsf_msgs.TeamProtos.Team.CYAN;
        onChanged();
        return this;
      }

      private java.util.List<org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.Route> routes_ =
        java.util.Collections.emptyList();
      private void ensureRoutesIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          routes_ = new java.util.ArrayList<org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.Route>(routes_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.Route, org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.Route.Builder, org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.RouteOrBuilder> routesBuilder_;

      /**
       * <code>repeated .llsf_msgs.Route routes = 5;</code>
       */
      public java.util.List<org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.Route> getRoutesList() {
        if (routesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(routes_);
        } else {
          return routesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .llsf_msgs.Route routes = 5;</code>
       */
      public int getRoutesCount() {
        if (routesBuilder_ == null) {
          return routes_.size();
        } else {
          return routesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .llsf_msgs.Route routes = 5;</code>
       */
      public org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.Route getRoutes(int index) {
        if (routesBuilder_ == null) {
          return routes_.get(index);
        } else {
          return routesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .llsf_msgs.Route routes = 5;</code>
       */
      public Builder setRoutes(
          int index, org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.Route value) {
        if (routesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRoutesIsMutable();
          routes_.set(index, value);
          onChanged();
        } else {
          routesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .llsf_msgs.Route routes = 5;</code>
       */
      public Builder setRoutes(
          int index, org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.Route.Builder builderForValue) {
        if (routesBuilder_ == null) {
          ensureRoutesIsMutable();
          routes_.set(index, builderForValue.build());
          onChanged();
        } else {
          routesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .llsf_msgs.Route routes = 5;</code>
       */
      public Builder addRoutes(org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.Route value) {
        if (routesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRoutesIsMutable();
          routes_.add(value);
          onChanged();
        } else {
          routesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .llsf_msgs.Route routes = 5;</code>
       */
      public Builder addRoutes(
          int index, org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.Route value) {
        if (routesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRoutesIsMutable();
          routes_.add(index, value);
          onChanged();
        } else {
          routesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .llsf_msgs.Route routes = 5;</code>
       */
      public Builder addRoutes(
          org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.Route.Builder builderForValue) {
        if (routesBuilder_ == null) {
          ensureRoutesIsMutable();
          routes_.add(builderForValue.build());
          onChanged();
        } else {
          routesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .llsf_msgs.Route routes = 5;</code>
       */
      public Builder addRoutes(
          int index, org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.Route.Builder builderForValue) {
        if (routesBuilder_ == null) {
          ensureRoutesIsMutable();
          routes_.add(index, builderForValue.build());
          onChanged();
        } else {
          routesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .llsf_msgs.Route routes = 5;</code>
       */
      public Builder addAllRoutes(
          java.lang.Iterable<? extends org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.Route> values) {
        if (routesBuilder_ == null) {
          ensureRoutesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, routes_);
          onChanged();
        } else {
          routesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .llsf_msgs.Route routes = 5;</code>
       */
      public Builder clearRoutes() {
        if (routesBuilder_ == null) {
          routes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          routesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .llsf_msgs.Route routes = 5;</code>
       */
      public Builder removeRoutes(int index) {
        if (routesBuilder_ == null) {
          ensureRoutesIsMutable();
          routes_.remove(index);
          onChanged();
        } else {
          routesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .llsf_msgs.Route routes = 5;</code>
       */
      public org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.Route.Builder getRoutesBuilder(
          int index) {
        return getRoutesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .llsf_msgs.Route routes = 5;</code>
       */
      public org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.RouteOrBuilder getRoutesOrBuilder(
          int index) {
        if (routesBuilder_ == null) {
          return routes_.get(index);  } else {
          return routesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .llsf_msgs.Route routes = 5;</code>
       */
      public java.util.List<? extends org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.RouteOrBuilder> 
           getRoutesOrBuilderList() {
        if (routesBuilder_ != null) {
          return routesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(routes_);
        }
      }
      /**
       * <code>repeated .llsf_msgs.Route routes = 5;</code>
       */
      public org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.Route.Builder addRoutesBuilder() {
        return getRoutesFieldBuilder().addBuilder(
            org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.Route.getDefaultInstance());
      }
      /**
       * <code>repeated .llsf_msgs.Route routes = 5;</code>
       */
      public org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.Route.Builder addRoutesBuilder(
          int index) {
        return getRoutesFieldBuilder().addBuilder(
            index, org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.Route.getDefaultInstance());
      }
      /**
       * <code>repeated .llsf_msgs.Route routes = 5;</code>
       */
      public java.util.List<org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.Route.Builder> 
           getRoutesBuilderList() {
        return getRoutesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.Route, org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.Route.Builder, org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.RouteOrBuilder> 
          getRoutesFieldBuilder() {
        if (routesBuilder_ == null) {
          routesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.Route, org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.Route.Builder, org.robocup_logistics.llsf_msgs.NavigationChallengeProtos.RouteOrBuilder>(
                  routes_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          routes_ = null;
        }
        return routesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:llsf_msgs.NavigationRoutes)
    }

    static {
      defaultInstance = new NavigationRoutes(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:llsf_msgs.NavigationRoutes)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_llsf_msgs_Route_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_llsf_msgs_Route_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_llsf_msgs_NavigationRoutes_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_llsf_msgs_NavigationRoutes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031NavigationChallenge.proto\022\tllsf_msgs\032\n" +
      "Team.proto\032\nZone.proto\"y\n\005Route\022\n\n\002id\030\001 " +
      "\002(\r\022\036\n\005route\030\002 \003(\0162\017.llsf_msgs.Zone\022 \n\007r" +
      "eached\030\003 \003(\0162\017.llsf_msgs.Zone\022\"\n\tremaini" +
      "ng\030\004 \003(\0162\017.llsf_msgs.Zone\"\202\001\n\020Navigation" +
      "Routes\022#\n\nteam_color\030\001 \002(\0162\017.llsf_msgs.T" +
      "eam\022 \n\006routes\030\005 \003(\0132\020.llsf_msgs.Route\"\'\n" +
      "\010CompType\022\014\n\007COMP_ID\020\320\017\022\r\n\010MSG_TYPE\020\372\001B<" +
      "\n\037org.robocup_logistics.llsf_msgsB\031Navig" +
      "ationChallengeProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.robocup_logistics.llsf_msgs.TeamProtos.getDescriptor(),
          org.robocup_logistics.llsf_msgs.ZoneProtos.getDescriptor(),
        }, assigner);
    internal_static_llsf_msgs_Route_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_llsf_msgs_Route_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_llsf_msgs_Route_descriptor,
        new java.lang.String[] { "Id", "Route", "Reached", "Remaining", });
    internal_static_llsf_msgs_NavigationRoutes_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_llsf_msgs_NavigationRoutes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_llsf_msgs_NavigationRoutes_descriptor,
        new java.lang.String[] { "TeamColor", "Routes", });
    org.robocup_logistics.llsf_msgs.TeamProtos.getDescriptor();
    org.robocup_logistics.llsf_msgs.ZoneProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
