// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Pose2D.proto

package org.robocup_logistics.llsf_msgs;

public final class Pose2DProtos {
  private Pose2DProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface Pose2DOrBuilder extends
      // @@protoc_insertion_point(interface_extends:llsf_msgs.Pose2D)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Time when this pose was measured
     * </pre>
     *
     * <code>required .llsf_msgs.Time timestamp = 1;</code>
     * @return Whether the timestamp field is set.
     */
    boolean hasTimestamp();
    /**
     * <pre>
     * Time when this pose was measured
     * </pre>
     *
     * <code>required .llsf_msgs.Time timestamp = 1;</code>
     * @return The timestamp.
     */
    org.robocup_logistics.llsf_msgs.TimeProtos.Time getTimestamp();
    /**
     * <pre>
     * Time when this pose was measured
     * </pre>
     *
     * <code>required .llsf_msgs.Time timestamp = 1;</code>
     */
    org.robocup_logistics.llsf_msgs.TimeProtos.TimeOrBuilder getTimestampOrBuilder();

    /**
     * <pre>
     * X/Y coordinates in meters
     * </pre>
     *
     * <code>required float x = 2;</code>
     * @return Whether the x field is set.
     */
    boolean hasX();
    /**
     * <pre>
     * X/Y coordinates in meters
     * </pre>
     *
     * <code>required float x = 2;</code>
     * @return The x.
     */
    float getX();

    /**
     * <code>required float y = 3;</code>
     * @return Whether the y field is set.
     */
    boolean hasY();
    /**
     * <code>required float y = 3;</code>
     * @return The y.
     */
    float getY();

    /**
     * <pre>
     * Orientation in rad
     * </pre>
     *
     * <code>required float ori = 4;</code>
     * @return Whether the ori field is set.
     */
    boolean hasOri();
    /**
     * <pre>
     * Orientation in rad
     * </pre>
     *
     * <code>required float ori = 4;</code>
     * @return The ori.
     */
    float getOri();
  }
  /**
   * <pre>
   * Pose information on 2D map
   * Data is relative to the LLSF field frame
   * </pre>
   *
   * Protobuf type {@code llsf_msgs.Pose2D}
   */
  public static final class Pose2D extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:llsf_msgs.Pose2D)
      Pose2DOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Pose2D.newBuilder() to construct.
    private Pose2D(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Pose2D() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Pose2D();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Pose2D(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              org.robocup_logistics.llsf_msgs.TimeProtos.Time.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) != 0)) {
                subBuilder = timestamp_.toBuilder();
              }
              timestamp_ = input.readMessage(org.robocup_logistics.llsf_msgs.TimeProtos.Time.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(timestamp_);
                timestamp_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              x_ = input.readFloat();
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              y_ = input.readFloat();
              break;
            }
            case 37: {
              bitField0_ |= 0x00000008;
              ori_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return internal_static_llsf_msgs_Pose2D_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return internal_static_llsf_msgs_Pose2D_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.robocup_logistics.llsf_msgs.Pose2DProtos.Pose2D.class, org.robocup_logistics.llsf_msgs.Pose2DProtos.Pose2D.Builder.class);
    }

    private int bitField0_;
    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private org.robocup_logistics.llsf_msgs.TimeProtos.Time timestamp_;
    /**
     * <pre>
     * Time when this pose was measured
     * </pre>
     *
     * <code>required .llsf_msgs.Time timestamp = 1;</code>
     * @return Whether the timestamp field is set.
     */
    @java.lang.Override
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Time when this pose was measured
     * </pre>
     *
     * <code>required .llsf_msgs.Time timestamp = 1;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public org.robocup_logistics.llsf_msgs.TimeProtos.Time getTimestamp() {
      return timestamp_ == null ? org.robocup_logistics.llsf_msgs.TimeProtos.Time.getDefaultInstance() : timestamp_;
    }
    /**
     * <pre>
     * Time when this pose was measured
     * </pre>
     *
     * <code>required .llsf_msgs.Time timestamp = 1;</code>
     */
    @java.lang.Override
    public org.robocup_logistics.llsf_msgs.TimeProtos.TimeOrBuilder getTimestampOrBuilder() {
      return timestamp_ == null ? org.robocup_logistics.llsf_msgs.TimeProtos.Time.getDefaultInstance() : timestamp_;
    }

    public static final int X_FIELD_NUMBER = 2;
    private float x_;
    /**
     * <pre>
     * X/Y coordinates in meters
     * </pre>
     *
     * <code>required float x = 2;</code>
     * @return Whether the x field is set.
     */
    @java.lang.Override
    public boolean hasX() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * X/Y coordinates in meters
     * </pre>
     *
     * <code>required float x = 2;</code>
     * @return The x.
     */
    @java.lang.Override
    public float getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 3;
    private float y_;
    /**
     * <code>required float y = 3;</code>
     * @return Whether the y field is set.
     */
    @java.lang.Override
    public boolean hasY() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required float y = 3;</code>
     * @return The y.
     */
    @java.lang.Override
    public float getY() {
      return y_;
    }

    public static final int ORI_FIELD_NUMBER = 4;
    private float ori_;
    /**
     * <pre>
     * Orientation in rad
     * </pre>
     *
     * <code>required float ori = 4;</code>
     * @return Whether the ori field is set.
     */
    @java.lang.Override
    public boolean hasOri() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * Orientation in rad
     * </pre>
     *
     * <code>required float ori = 4;</code>
     * @return The ori.
     */
    @java.lang.Override
    public float getOri() {
      return ori_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasX()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasY()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOri()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getTimestamp().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getTimestamp());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeFloat(2, x_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeFloat(3, y_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeFloat(4, ori_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getTimestamp());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, x_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, y_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, ori_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.robocup_logistics.llsf_msgs.Pose2DProtos.Pose2D)) {
        return super.equals(obj);
      }
      org.robocup_logistics.llsf_msgs.Pose2DProtos.Pose2D other = (org.robocup_logistics.llsf_msgs.Pose2DProtos.Pose2D) obj;

      if (hasTimestamp() != other.hasTimestamp()) return false;
      if (hasTimestamp()) {
        if (!getTimestamp()
            .equals(other.getTimestamp())) return false;
      }
      if (hasX() != other.hasX()) return false;
      if (hasX()) {
        if (java.lang.Float.floatToIntBits(getX())
            != java.lang.Float.floatToIntBits(
                other.getX())) return false;
      }
      if (hasY() != other.hasY()) return false;
      if (hasY()) {
        if (java.lang.Float.floatToIntBits(getY())
            != java.lang.Float.floatToIntBits(
                other.getY())) return false;
      }
      if (hasOri() != other.hasOri()) return false;
      if (hasOri()) {
        if (java.lang.Float.floatToIntBits(getOri())
            != java.lang.Float.floatToIntBits(
                other.getOri())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTimestamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + getTimestamp().hashCode();
      }
      if (hasX()) {
        hash = (37 * hash) + X_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getX());
      }
      if (hasY()) {
        hash = (37 * hash) + Y_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getY());
      }
      if (hasOri()) {
        hash = (37 * hash) + ORI_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getOri());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.robocup_logistics.llsf_msgs.Pose2DProtos.Pose2D parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.robocup_logistics.llsf_msgs.Pose2DProtos.Pose2D parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.robocup_logistics.llsf_msgs.Pose2DProtos.Pose2D parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.robocup_logistics.llsf_msgs.Pose2DProtos.Pose2D parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.robocup_logistics.llsf_msgs.Pose2DProtos.Pose2D parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.robocup_logistics.llsf_msgs.Pose2DProtos.Pose2D parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.robocup_logistics.llsf_msgs.Pose2DProtos.Pose2D parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.robocup_logistics.llsf_msgs.Pose2DProtos.Pose2D parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.robocup_logistics.llsf_msgs.Pose2DProtos.Pose2D parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.robocup_logistics.llsf_msgs.Pose2DProtos.Pose2D parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.robocup_logistics.llsf_msgs.Pose2DProtos.Pose2D parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.robocup_logistics.llsf_msgs.Pose2DProtos.Pose2D parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.robocup_logistics.llsf_msgs.Pose2DProtos.Pose2D prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Pose information on 2D map
     * Data is relative to the LLSF field frame
     * </pre>
     *
     * Protobuf type {@code llsf_msgs.Pose2D}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:llsf_msgs.Pose2D)
        org.robocup_logistics.llsf_msgs.Pose2DProtos.Pose2DOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return internal_static_llsf_msgs_Pose2D_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return internal_static_llsf_msgs_Pose2D_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.robocup_logistics.llsf_msgs.Pose2DProtos.Pose2D.class, org.robocup_logistics.llsf_msgs.Pose2DProtos.Pose2D.Builder.class);
      }

      // Construct using org.robocup_logistics.llsf_msgs.Pose2DProtos.Pose2D.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getTimestampFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (timestampBuilder_ == null) {
          timestamp_ = null;
        } else {
          timestampBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000002);
        y_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        ori_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return internal_static_llsf_msgs_Pose2D_descriptor;
      }

      @java.lang.Override
      public org.robocup_logistics.llsf_msgs.Pose2DProtos.Pose2D getDefaultInstanceForType() {
        return getDefaultInstance();
      }

      @java.lang.Override
      public org.robocup_logistics.llsf_msgs.Pose2DProtos.Pose2D build() {
        org.robocup_logistics.llsf_msgs.Pose2DProtos.Pose2D result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.robocup_logistics.llsf_msgs.Pose2DProtos.Pose2D buildPartial() {
        org.robocup_logistics.llsf_msgs.Pose2DProtos.Pose2D result = new org.robocup_logistics.llsf_msgs.Pose2DProtos.Pose2D(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          if (timestampBuilder_ == null) {
            result.timestamp_ = timestamp_;
          } else {
            result.timestamp_ = timestampBuilder_.build();
          }
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.x_ = x_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.y_ = y_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.ori_ = ori_;
          to_bitField0_ |= 0x00000008;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.robocup_logistics.llsf_msgs.Pose2DProtos.Pose2D) {
          return mergeFrom((org.robocup_logistics.llsf_msgs.Pose2DProtos.Pose2D)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.robocup_logistics.llsf_msgs.Pose2DProtos.Pose2D other) {
        if (other == getDefaultInstance()) return this;
        if (other.hasTimestamp()) {
          mergeTimestamp(other.getTimestamp());
        }
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        if (other.hasOri()) {
          setOri(other.getOri());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasTimestamp()) {
          return false;
        }
        if (!hasX()) {
          return false;
        }
        if (!hasY()) {
          return false;
        }
        if (!hasOri()) {
          return false;
        }
        if (!getTimestamp().isInitialized()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.robocup_logistics.llsf_msgs.Pose2DProtos.Pose2D parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.robocup_logistics.llsf_msgs.Pose2DProtos.Pose2D) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private org.robocup_logistics.llsf_msgs.TimeProtos.Time timestamp_;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.robocup_logistics.llsf_msgs.TimeProtos.Time, org.robocup_logistics.llsf_msgs.TimeProtos.Time.Builder, org.robocup_logistics.llsf_msgs.TimeProtos.TimeOrBuilder> timestampBuilder_;
      /**
       * <pre>
       * Time when this pose was measured
       * </pre>
       *
       * <code>required .llsf_msgs.Time timestamp = 1;</code>
       * @return Whether the timestamp field is set.
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * Time when this pose was measured
       * </pre>
       *
       * <code>required .llsf_msgs.Time timestamp = 1;</code>
       * @return The timestamp.
       */
      public org.robocup_logistics.llsf_msgs.TimeProtos.Time getTimestamp() {
        if (timestampBuilder_ == null) {
          return timestamp_ == null ? org.robocup_logistics.llsf_msgs.TimeProtos.Time.getDefaultInstance() : timestamp_;
        } else {
          return timestampBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * Time when this pose was measured
       * </pre>
       *
       * <code>required .llsf_msgs.Time timestamp = 1;</code>
       */
      public Builder setTimestamp(org.robocup_logistics.llsf_msgs.TimeProtos.Time value) {
        if (timestampBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          timestamp_ = value;
          onChanged();
        } else {
          timestampBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <pre>
       * Time when this pose was measured
       * </pre>
       *
       * <code>required .llsf_msgs.Time timestamp = 1;</code>
       */
      public Builder setTimestamp(
          org.robocup_logistics.llsf_msgs.TimeProtos.Time.Builder builderForValue) {
        if (timestampBuilder_ == null) {
          timestamp_ = builderForValue.build();
          onChanged();
        } else {
          timestampBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <pre>
       * Time when this pose was measured
       * </pre>
       *
       * <code>required .llsf_msgs.Time timestamp = 1;</code>
       */
      public Builder mergeTimestamp(org.robocup_logistics.llsf_msgs.TimeProtos.Time value) {
        if (timestampBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
              timestamp_ != null &&
              timestamp_ != org.robocup_logistics.llsf_msgs.TimeProtos.Time.getDefaultInstance()) {
            timestamp_ =
              org.robocup_logistics.llsf_msgs.TimeProtos.Time.newBuilder(timestamp_).mergeFrom(value).buildPartial();
          } else {
            timestamp_ = value;
          }
          onChanged();
        } else {
          timestampBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <pre>
       * Time when this pose was measured
       * </pre>
       *
       * <code>required .llsf_msgs.Time timestamp = 1;</code>
       */
      public Builder clearTimestamp() {
        if (timestampBuilder_ == null) {
          timestamp_ = null;
          onChanged();
        } else {
          timestampBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <pre>
       * Time when this pose was measured
       * </pre>
       *
       * <code>required .llsf_msgs.Time timestamp = 1;</code>
       */
      public org.robocup_logistics.llsf_msgs.TimeProtos.Time.Builder getTimestampBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getTimestampFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * Time when this pose was measured
       * </pre>
       *
       * <code>required .llsf_msgs.Time timestamp = 1;</code>
       */
      public org.robocup_logistics.llsf_msgs.TimeProtos.TimeOrBuilder getTimestampOrBuilder() {
        if (timestampBuilder_ != null) {
          return timestampBuilder_.getMessageOrBuilder();
        } else {
          return timestamp_ == null ?
              org.robocup_logistics.llsf_msgs.TimeProtos.Time.getDefaultInstance() : timestamp_;
        }
      }
      /**
       * <pre>
       * Time when this pose was measured
       * </pre>
       *
       * <code>required .llsf_msgs.Time timestamp = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.robocup_logistics.llsf_msgs.TimeProtos.Time, org.robocup_logistics.llsf_msgs.TimeProtos.Time.Builder, org.robocup_logistics.llsf_msgs.TimeProtos.TimeOrBuilder> 
          getTimestampFieldBuilder() {
        if (timestampBuilder_ == null) {
          timestampBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.robocup_logistics.llsf_msgs.TimeProtos.Time, org.robocup_logistics.llsf_msgs.TimeProtos.Time.Builder, org.robocup_logistics.llsf_msgs.TimeProtos.TimeOrBuilder>(
                  getTimestamp(),
                  getParentForChildren(),
                  isClean());
          timestamp_ = null;
        }
        return timestampBuilder_;
      }

      private float x_ ;
      /**
       * <pre>
       * X/Y coordinates in meters
       * </pre>
       *
       * <code>required float x = 2;</code>
       * @return Whether the x field is set.
       */
      @java.lang.Override
      public boolean hasX() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * X/Y coordinates in meters
       * </pre>
       *
       * <code>required float x = 2;</code>
       * @return The x.
       */
      @java.lang.Override
      public float getX() {
        return x_;
      }
      /**
       * <pre>
       * X/Y coordinates in meters
       * </pre>
       *
       * <code>required float x = 2;</code>
       * @param value The x to set.
       * @return This builder for chaining.
       */
      public Builder setX(float value) {
        bitField0_ |= 0x00000002;
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * X/Y coordinates in meters
       * </pre>
       *
       * <code>required float x = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000002);
        x_ = 0F;
        onChanged();
        return this;
      }

      private float y_ ;
      /**
       * <code>required float y = 3;</code>
       * @return Whether the y field is set.
       */
      @java.lang.Override
      public boolean hasY() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required float y = 3;</code>
       * @return The y.
       */
      @java.lang.Override
      public float getY() {
        return y_;
      }
      /**
       * <code>required float y = 3;</code>
       * @param value The y to set.
       * @return This builder for chaining.
       */
      public Builder setY(float value) {
        bitField0_ |= 0x00000004;
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float y = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000004);
        y_ = 0F;
        onChanged();
        return this;
      }

      private float ori_ ;
      /**
       * <pre>
       * Orientation in rad
       * </pre>
       *
       * <code>required float ori = 4;</code>
       * @return Whether the ori field is set.
       */
      @java.lang.Override
      public boolean hasOri() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <pre>
       * Orientation in rad
       * </pre>
       *
       * <code>required float ori = 4;</code>
       * @return The ori.
       */
      @java.lang.Override
      public float getOri() {
        return ori_;
      }
      /**
       * <pre>
       * Orientation in rad
       * </pre>
       *
       * <code>required float ori = 4;</code>
       * @param value The ori to set.
       * @return This builder for chaining.
       */
      public Builder setOri(float value) {
        bitField0_ |= 0x00000008;
        ori_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Orientation in rad
       * </pre>
       *
       * <code>required float ori = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearOri() {
        bitField0_ = (bitField0_ & ~0x00000008);
        ori_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:llsf_msgs.Pose2D)
    }

    // @@protoc_insertion_point(class_scope:llsf_msgs.Pose2D)
    private static final org.robocup_logistics.llsf_msgs.Pose2DProtos.Pose2D DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.robocup_logistics.llsf_msgs.Pose2DProtos.Pose2D();
    }

    public static org.robocup_logistics.llsf_msgs.Pose2DProtos.Pose2D getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Pose2D>
        PARSER = new com.google.protobuf.AbstractParser<Pose2D>() {
      @java.lang.Override
      public Pose2D parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Pose2D(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Pose2D> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Pose2D> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.robocup_logistics.llsf_msgs.Pose2DProtos.Pose2D getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_llsf_msgs_Pose2D_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_llsf_msgs_Pose2D_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Pose2D.proto\022\tllsf_msgs\032\nTime.proto\"O\n" +
      "\006Pose2D\022\"\n\ttimestamp\030\001 \002(\0132\017.llsf_msgs.T" +
      "ime\022\t\n\001x\030\002 \002(\002\022\t\n\001y\030\003 \002(\002\022\013\n\003ori\030\004 \002(\002B/" +
      "\n\037org.robocup_logistics.llsf_msgsB\014Pose2" +
      "DProtos"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.robocup_logistics.llsf_msgs.TimeProtos.getDescriptor(),
        });
    internal_static_llsf_msgs_Pose2D_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_llsf_msgs_Pose2D_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_llsf_msgs_Pose2D_descriptor,
        new java.lang.String[] { "Timestamp", "X", "Y", "Ori", });
    org.robocup_logistics.llsf_msgs.TimeProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
