// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RingInfo.proto

package org.robocup_logistics.llsf_msgs;

public final class RingInfoProtos {
  private RingInfoProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RingOrBuilder extends
      // @@protoc_insertion_point(interface_extends:llsf_msgs.Ring)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Ring color this concerns
     * </pre>
     *
     * <code>required .llsf_msgs.RingColor ring_color = 1;</code>
     * @return Whether the ringColor field is set.
     */
    boolean hasRingColor();
    /**
     * <pre>
     * Ring color this concerns
     * </pre>
     *
     * <code>required .llsf_msgs.RingColor ring_color = 1;</code>
     * @return The ringColor.
     */
    org.robocup_logistics.llsf_msgs.ProductColorProtos.RingColor getRingColor();

    /**
     * <pre>
     * number of additional bases
     * required to produce this ring type
     * </pre>
     *
     * <code>required uint32 raw_material = 2;</code>
     * @return Whether the rawMaterial field is set.
     */
    boolean hasRawMaterial();
    /**
     * <pre>
     * number of additional bases
     * required to produce this ring type
     * </pre>
     *
     * <code>required uint32 raw_material = 2;</code>
     * @return The rawMaterial.
     */
    int getRawMaterial();
  }
  /**
   * Protobuf type {@code llsf_msgs.Ring}
   */
  public static final class Ring extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:llsf_msgs.Ring)
      RingOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Ring.newBuilder() to construct.
    private Ring(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Ring() {
      ringColor_ = 1;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Ring();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Ring(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              org.robocup_logistics.llsf_msgs.ProductColorProtos.RingColor value = org.robocup_logistics.llsf_msgs.ProductColorProtos.RingColor.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                ringColor_ = rawValue;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              rawMaterial_ = input.readUInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return internal_static_llsf_msgs_Ring_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return internal_static_llsf_msgs_Ring_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring.class, org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring.Builder.class);
    }

    private int bitField0_;
    public static final int RING_COLOR_FIELD_NUMBER = 1;
    private int ringColor_;
    /**
     * <pre>
     * Ring color this concerns
     * </pre>
     *
     * <code>required .llsf_msgs.RingColor ring_color = 1;</code>
     * @return Whether the ringColor field is set.
     */
    @java.lang.Override public boolean hasRingColor() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Ring color this concerns
     * </pre>
     *
     * <code>required .llsf_msgs.RingColor ring_color = 1;</code>
     * @return The ringColor.
     */
    @java.lang.Override public org.robocup_logistics.llsf_msgs.ProductColorProtos.RingColor getRingColor() {
      @SuppressWarnings("deprecation")
      org.robocup_logistics.llsf_msgs.ProductColorProtos.RingColor result = org.robocup_logistics.llsf_msgs.ProductColorProtos.RingColor.valueOf(ringColor_);
      return result == null ? org.robocup_logistics.llsf_msgs.ProductColorProtos.RingColor.RING_BLUE : result;
    }

    public static final int RAW_MATERIAL_FIELD_NUMBER = 2;
    private int rawMaterial_;
    /**
     * <pre>
     * number of additional bases
     * required to produce this ring type
     * </pre>
     *
     * <code>required uint32 raw_material = 2;</code>
     * @return Whether the rawMaterial field is set.
     */
    @java.lang.Override
    public boolean hasRawMaterial() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * number of additional bases
     * required to produce this ring type
     * </pre>
     *
     * <code>required uint32 raw_material = 2;</code>
     * @return The rawMaterial.
     */
    @java.lang.Override
    public int getRawMaterial() {
      return rawMaterial_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasRingColor()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRawMaterial()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeEnum(1, ringColor_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeUInt32(2, rawMaterial_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, ringColor_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, rawMaterial_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring)) {
        return super.equals(obj);
      }
      org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring other = (org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring) obj;

      if (hasRingColor() != other.hasRingColor()) return false;
      if (hasRingColor()) {
        if (ringColor_ != other.ringColor_) return false;
      }
      if (hasRawMaterial() != other.hasRawMaterial()) return false;
      if (hasRawMaterial()) {
        if (getRawMaterial()
            != other.getRawMaterial()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRingColor()) {
        hash = (37 * hash) + RING_COLOR_FIELD_NUMBER;
        hash = (53 * hash) + ringColor_;
      }
      if (hasRawMaterial()) {
        hash = (37 * hash) + RAW_MATERIAL_FIELD_NUMBER;
        hash = (53 * hash) + getRawMaterial();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code llsf_msgs.Ring}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:llsf_msgs.Ring)
        org.robocup_logistics.llsf_msgs.RingInfoProtos.RingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return internal_static_llsf_msgs_Ring_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return internal_static_llsf_msgs_Ring_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring.class, org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring.Builder.class);
      }

      // Construct using org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        ringColor_ = 1;
        bitField0_ = (bitField0_ & ~0x00000001);
        rawMaterial_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return internal_static_llsf_msgs_Ring_descriptor;
      }

      @java.lang.Override
      public org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring getDefaultInstanceForType() {
        return getDefaultInstance();
      }

      @java.lang.Override
      public org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring build() {
        org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring buildPartial() {
        org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring result = new org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ringColor_ = ringColor_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.rawMaterial_ = rawMaterial_;
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring) {
          return mergeFrom((org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring other) {
        if (other == getDefaultInstance()) return this;
        if (other.hasRingColor()) {
          setRingColor(other.getRingColor());
        }
        if (other.hasRawMaterial()) {
          setRawMaterial(other.getRawMaterial());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasRingColor()) {
          return false;
        }
        if (!hasRawMaterial()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int ringColor_ = 1;
      /**
       * <pre>
       * Ring color this concerns
       * </pre>
       *
       * <code>required .llsf_msgs.RingColor ring_color = 1;</code>
       * @return Whether the ringColor field is set.
       */
      @java.lang.Override public boolean hasRingColor() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * Ring color this concerns
       * </pre>
       *
       * <code>required .llsf_msgs.RingColor ring_color = 1;</code>
       * @return The ringColor.
       */
      @java.lang.Override
      public org.robocup_logistics.llsf_msgs.ProductColorProtos.RingColor getRingColor() {
        @SuppressWarnings("deprecation")
        org.robocup_logistics.llsf_msgs.ProductColorProtos.RingColor result = org.robocup_logistics.llsf_msgs.ProductColorProtos.RingColor.valueOf(ringColor_);
        return result == null ? org.robocup_logistics.llsf_msgs.ProductColorProtos.RingColor.RING_BLUE : result;
      }
      /**
       * <pre>
       * Ring color this concerns
       * </pre>
       *
       * <code>required .llsf_msgs.RingColor ring_color = 1;</code>
       * @param value The ringColor to set.
       * @return This builder for chaining.
       */
      public Builder setRingColor(org.robocup_logistics.llsf_msgs.ProductColorProtos.RingColor value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        ringColor_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Ring color this concerns
       * </pre>
       *
       * <code>required .llsf_msgs.RingColor ring_color = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRingColor() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ringColor_ = 1;
        onChanged();
        return this;
      }

      private int rawMaterial_ ;
      /**
       * <pre>
       * number of additional bases
       * required to produce this ring type
       * </pre>
       *
       * <code>required uint32 raw_material = 2;</code>
       * @return Whether the rawMaterial field is set.
       */
      @java.lang.Override
      public boolean hasRawMaterial() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * number of additional bases
       * required to produce this ring type
       * </pre>
       *
       * <code>required uint32 raw_material = 2;</code>
       * @return The rawMaterial.
       */
      @java.lang.Override
      public int getRawMaterial() {
        return rawMaterial_;
      }
      /**
       * <pre>
       * number of additional bases
       * required to produce this ring type
       * </pre>
       *
       * <code>required uint32 raw_material = 2;</code>
       * @param value The rawMaterial to set.
       * @return This builder for chaining.
       */
      public Builder setRawMaterial(int value) {
        bitField0_ |= 0x00000002;
        rawMaterial_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * number of additional bases
       * required to produce this ring type
       * </pre>
       *
       * <code>required uint32 raw_material = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRawMaterial() {
        bitField0_ = (bitField0_ & ~0x00000002);
        rawMaterial_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:llsf_msgs.Ring)
    }

    // @@protoc_insertion_point(class_scope:llsf_msgs.Ring)
    private static final org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring();
    }

    public static org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Ring>
        PARSER = new com.google.protobuf.AbstractParser<Ring>() {
      @java.lang.Override
      public Ring parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Ring(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Ring> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Ring> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RingInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:llsf_msgs.RingInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * List of all known pucks
     * </pre>
     *
     * <code>repeated .llsf_msgs.Ring rings = 1;</code>
     */
    java.util.List<org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring> 
        getRingsList();
    /**
     * <pre>
     * List of all known pucks
     * </pre>
     *
     * <code>repeated .llsf_msgs.Ring rings = 1;</code>
     */
    org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring getRings(int index);
    /**
     * <pre>
     * List of all known pucks
     * </pre>
     *
     * <code>repeated .llsf_msgs.Ring rings = 1;</code>
     */
    int getRingsCount();
    /**
     * <pre>
     * List of all known pucks
     * </pre>
     *
     * <code>repeated .llsf_msgs.Ring rings = 1;</code>
     */
    java.util.List<? extends org.robocup_logistics.llsf_msgs.RingInfoProtos.RingOrBuilder> 
        getRingsOrBuilderList();
    /**
     * <pre>
     * List of all known pucks
     * </pre>
     *
     * <code>repeated .llsf_msgs.Ring rings = 1;</code>
     */
    org.robocup_logistics.llsf_msgs.RingInfoProtos.RingOrBuilder getRingsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code llsf_msgs.RingInfo}
   */
  public static final class RingInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:llsf_msgs.RingInfo)
      RingInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RingInfo.newBuilder() to construct.
    private RingInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RingInfo() {
      rings_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new RingInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RingInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                rings_ = new java.util.ArrayList<org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring>();
                mutable_bitField0_ |= 0x00000001;
              }
              rings_.add(
                  input.readMessage(org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          rings_ = java.util.Collections.unmodifiableList(rings_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return internal_static_llsf_msgs_RingInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return internal_static_llsf_msgs_RingInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo.class, org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo.Builder.class);
    }

    /**
     * Protobuf enum {@code llsf_msgs.RingInfo.CompType}
     */
    public enum CompType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>COMP_ID = 2000;</code>
       */
      COMP_ID(2000),
      /**
       * <code>MSG_TYPE = 110;</code>
       */
      MSG_TYPE(110),
      ;

      /**
       * <code>COMP_ID = 2000;</code>
       */
      public static final int COMP_ID_VALUE = 2000;
      /**
       * <code>MSG_TYPE = 110;</code>
       */
      public static final int MSG_TYPE_VALUE = 110;


      public final int getNumber() {
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static CompType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static CompType forNumber(int value) {
        switch (value) {
          case 2000: return COMP_ID;
          case 110: return MSG_TYPE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<CompType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          CompType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CompType>() {
              public CompType findValueByNumber(int number) {
                return CompType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo.getDescriptor().getEnumTypes().get(0);
      }

      private static final CompType[] VALUES = values();

      public static CompType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private CompType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:llsf_msgs.RingInfo.CompType)
    }

    public static final int RINGS_FIELD_NUMBER = 1;
    private java.util.List<org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring> rings_;
    /**
     * <pre>
     * List of all known pucks
     * </pre>
     *
     * <code>repeated .llsf_msgs.Ring rings = 1;</code>
     */
    @java.lang.Override
    public java.util.List<org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring> getRingsList() {
      return rings_;
    }
    /**
     * <pre>
     * List of all known pucks
     * </pre>
     *
     * <code>repeated .llsf_msgs.Ring rings = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends org.robocup_logistics.llsf_msgs.RingInfoProtos.RingOrBuilder> 
        getRingsOrBuilderList() {
      return rings_;
    }
    /**
     * <pre>
     * List of all known pucks
     * </pre>
     *
     * <code>repeated .llsf_msgs.Ring rings = 1;</code>
     */
    @java.lang.Override
    public int getRingsCount() {
      return rings_.size();
    }
    /**
     * <pre>
     * List of all known pucks
     * </pre>
     *
     * <code>repeated .llsf_msgs.Ring rings = 1;</code>
     */
    @java.lang.Override
    public org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring getRings(int index) {
      return rings_.get(index);
    }
    /**
     * <pre>
     * List of all known pucks
     * </pre>
     *
     * <code>repeated .llsf_msgs.Ring rings = 1;</code>
     */
    @java.lang.Override
    public org.robocup_logistics.llsf_msgs.RingInfoProtos.RingOrBuilder getRingsOrBuilder(
        int index) {
      return rings_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getRingsCount(); i++) {
        if (!getRings(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < rings_.size(); i++) {
        output.writeMessage(1, rings_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < rings_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, rings_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo)) {
        return super.equals(obj);
      }
      org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo other = (org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo) obj;

      if (!getRingsList()
          .equals(other.getRingsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getRingsCount() > 0) {
        hash = (37 * hash) + RINGS_FIELD_NUMBER;
        hash = (53 * hash) + getRingsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code llsf_msgs.RingInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:llsf_msgs.RingInfo)
        org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return internal_static_llsf_msgs_RingInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return internal_static_llsf_msgs_RingInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo.class, org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo.Builder.class);
      }

      // Construct using org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getRingsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (ringsBuilder_ == null) {
          rings_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ringsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return internal_static_llsf_msgs_RingInfo_descriptor;
      }

      @java.lang.Override
      public org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo getDefaultInstanceForType() {
        return getDefaultInstance();
      }

      @java.lang.Override
      public org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo build() {
        org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo buildPartial() {
        org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo result = new org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo(this);
        int from_bitField0_ = bitField0_;
        if (ringsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            rings_ = java.util.Collections.unmodifiableList(rings_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.rings_ = rings_;
        } else {
          result.rings_ = ringsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo) {
          return mergeFrom((org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo other) {
        if (other == getDefaultInstance()) return this;
        if (ringsBuilder_ == null) {
          if (!other.rings_.isEmpty()) {
            if (rings_.isEmpty()) {
              rings_ = other.rings_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureRingsIsMutable();
              rings_.addAll(other.rings_);
            }
            onChanged();
          }
        } else {
          if (!other.rings_.isEmpty()) {
            if (ringsBuilder_.isEmpty()) {
              ringsBuilder_.dispose();
              ringsBuilder_ = null;
              rings_ = other.rings_;
              bitField0_ = (bitField0_ & ~0x00000001);
              ringsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getRingsFieldBuilder() : null;
            } else {
              ringsBuilder_.addAllMessages(other.rings_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        for (int i = 0; i < getRingsCount(); i++) {
          if (!getRings(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring> rings_ =
        java.util.Collections.emptyList();
      private void ensureRingsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          rings_ = new java.util.ArrayList<org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring>(rings_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring, org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring.Builder, org.robocup_logistics.llsf_msgs.RingInfoProtos.RingOrBuilder> ringsBuilder_;

      /**
       * <pre>
       * List of all known pucks
       * </pre>
       *
       * <code>repeated .llsf_msgs.Ring rings = 1;</code>
       */
      public java.util.List<org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring> getRingsList() {
        if (ringsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(rings_);
        } else {
          return ringsBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * List of all known pucks
       * </pre>
       *
       * <code>repeated .llsf_msgs.Ring rings = 1;</code>
       */
      public int getRingsCount() {
        if (ringsBuilder_ == null) {
          return rings_.size();
        } else {
          return ringsBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * List of all known pucks
       * </pre>
       *
       * <code>repeated .llsf_msgs.Ring rings = 1;</code>
       */
      public org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring getRings(int index) {
        if (ringsBuilder_ == null) {
          return rings_.get(index);
        } else {
          return ringsBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * List of all known pucks
       * </pre>
       *
       * <code>repeated .llsf_msgs.Ring rings = 1;</code>
       */
      public Builder setRings(
          int index, org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring value) {
        if (ringsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRingsIsMutable();
          rings_.set(index, value);
          onChanged();
        } else {
          ringsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * List of all known pucks
       * </pre>
       *
       * <code>repeated .llsf_msgs.Ring rings = 1;</code>
       */
      public Builder setRings(
          int index, org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring.Builder builderForValue) {
        if (ringsBuilder_ == null) {
          ensureRingsIsMutable();
          rings_.set(index, builderForValue.build());
          onChanged();
        } else {
          ringsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * List of all known pucks
       * </pre>
       *
       * <code>repeated .llsf_msgs.Ring rings = 1;</code>
       */
      public Builder addRings(org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring value) {
        if (ringsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRingsIsMutable();
          rings_.add(value);
          onChanged();
        } else {
          ringsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * List of all known pucks
       * </pre>
       *
       * <code>repeated .llsf_msgs.Ring rings = 1;</code>
       */
      public Builder addRings(
          int index, org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring value) {
        if (ringsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRingsIsMutable();
          rings_.add(index, value);
          onChanged();
        } else {
          ringsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * List of all known pucks
       * </pre>
       *
       * <code>repeated .llsf_msgs.Ring rings = 1;</code>
       */
      public Builder addRings(
          org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring.Builder builderForValue) {
        if (ringsBuilder_ == null) {
          ensureRingsIsMutable();
          rings_.add(builderForValue.build());
          onChanged();
        } else {
          ringsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * List of all known pucks
       * </pre>
       *
       * <code>repeated .llsf_msgs.Ring rings = 1;</code>
       */
      public Builder addRings(
          int index, org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring.Builder builderForValue) {
        if (ringsBuilder_ == null) {
          ensureRingsIsMutable();
          rings_.add(index, builderForValue.build());
          onChanged();
        } else {
          ringsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * List of all known pucks
       * </pre>
       *
       * <code>repeated .llsf_msgs.Ring rings = 1;</code>
       */
      public Builder addAllRings(
          java.lang.Iterable<? extends org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring> values) {
        if (ringsBuilder_ == null) {
          ensureRingsIsMutable();
          addAll(
              values, rings_);
          onChanged();
        } else {
          ringsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * List of all known pucks
       * </pre>
       *
       * <code>repeated .llsf_msgs.Ring rings = 1;</code>
       */
      public Builder clearRings() {
        if (ringsBuilder_ == null) {
          rings_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          ringsBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * List of all known pucks
       * </pre>
       *
       * <code>repeated .llsf_msgs.Ring rings = 1;</code>
       */
      public Builder removeRings(int index) {
        if (ringsBuilder_ == null) {
          ensureRingsIsMutable();
          rings_.remove(index);
          onChanged();
        } else {
          ringsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * List of all known pucks
       * </pre>
       *
       * <code>repeated .llsf_msgs.Ring rings = 1;</code>
       */
      public org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring.Builder getRingsBuilder(
          int index) {
        return getRingsFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * List of all known pucks
       * </pre>
       *
       * <code>repeated .llsf_msgs.Ring rings = 1;</code>
       */
      public org.robocup_logistics.llsf_msgs.RingInfoProtos.RingOrBuilder getRingsOrBuilder(
          int index) {
        if (ringsBuilder_ == null) {
          return rings_.get(index);  } else {
          return ringsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * List of all known pucks
       * </pre>
       *
       * <code>repeated .llsf_msgs.Ring rings = 1;</code>
       */
      public java.util.List<? extends org.robocup_logistics.llsf_msgs.RingInfoProtos.RingOrBuilder> 
           getRingsOrBuilderList() {
        if (ringsBuilder_ != null) {
          return ringsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(rings_);
        }
      }
      /**
       * <pre>
       * List of all known pucks
       * </pre>
       *
       * <code>repeated .llsf_msgs.Ring rings = 1;</code>
       */
      public org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring.Builder addRingsBuilder() {
        return getRingsFieldBuilder().addBuilder(
            org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring.getDefaultInstance());
      }
      /**
       * <pre>
       * List of all known pucks
       * </pre>
       *
       * <code>repeated .llsf_msgs.Ring rings = 1;</code>
       */
      public org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring.Builder addRingsBuilder(
          int index) {
        return getRingsFieldBuilder().addBuilder(
            index, org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring.getDefaultInstance());
      }
      /**
       * <pre>
       * List of all known pucks
       * </pre>
       *
       * <code>repeated .llsf_msgs.Ring rings = 1;</code>
       */
      public java.util.List<org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring.Builder> 
           getRingsBuilderList() {
        return getRingsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring, org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring.Builder, org.robocup_logistics.llsf_msgs.RingInfoProtos.RingOrBuilder> 
          getRingsFieldBuilder() {
        if (ringsBuilder_ == null) {
          ringsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring, org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring.Builder, org.robocup_logistics.llsf_msgs.RingInfoProtos.RingOrBuilder>(
                  rings_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          rings_ = null;
        }
        return ringsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:llsf_msgs.RingInfo)
    }

    // @@protoc_insertion_point(class_scope:llsf_msgs.RingInfo)
    private static final org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo();
    }

    public static org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<RingInfo>
        PARSER = new com.google.protobuf.AbstractParser<RingInfo>() {
      @java.lang.Override
      public RingInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RingInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RingInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RingInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_llsf_msgs_Ring_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_llsf_msgs_Ring_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_llsf_msgs_RingInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_llsf_msgs_RingInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016RingInfo.proto\022\tllsf_msgs\032\022ProductColo" +
      "r.proto\"F\n\004Ring\022(\n\nring_color\030\001 \002(\0162\024.ll" +
      "sf_msgs.RingColor\022\024\n\014raw_material\030\002 \002(\r\"" +
      "R\n\010RingInfo\022\036\n\005rings\030\001 \003(\0132\017.llsf_msgs.R" +
      "ing\"&\n\010CompType\022\014\n\007COMP_ID\020\320\017\022\014\n\010MSG_TYP" +
      "E\020nB1\n\037org.robocup_logistics.llsf_msgsB\016" +
      "RingInfoProtos"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.robocup_logistics.llsf_msgs.ProductColorProtos.getDescriptor(),
        });
    internal_static_llsf_msgs_Ring_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_llsf_msgs_Ring_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_llsf_msgs_Ring_descriptor,
        new java.lang.String[] { "RingColor", "RawMaterial", });
    internal_static_llsf_msgs_RingInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_llsf_msgs_RingInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_llsf_msgs_RingInfo_descriptor,
        new java.lang.String[] { "Rings", });
    org.robocup_logistics.llsf_msgs.ProductColorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
