// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RobotCommands.proto

package org.robocup_logistics.llsf_msgs;

public final class RobotCommandsProtos {
  private RobotCommandsProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SetRobotMaintenanceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:llsf_msgs.SetRobotMaintenance)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Number of robot to set state
     * </pre>
     *
     * <code>required uint32 robot_number = 1;</code>
     * @return Whether the robotNumber field is set.
     */
    boolean hasRobotNumber();
    /**
     * <pre>
     * Number of robot to set state
     * </pre>
     *
     * <code>required uint32 robot_number = 1;</code>
     * @return The robotNumber.
     */
    int getRobotNumber();

    /**
     * <pre>
     * True to activate maintenance,
     * false to bring back robot
     * </pre>
     *
     * <code>required bool maintenance = 3;</code>
     * @return Whether the maintenance field is set.
     */
    boolean hasMaintenance();
    /**
     * <pre>
     * True to activate maintenance,
     * false to bring back robot
     * </pre>
     *
     * <code>required bool maintenance = 3;</code>
     * @return The maintenance.
     */
    boolean getMaintenance();

    /**
     * <pre>
     * Team the robot belongs to
     * </pre>
     *
     * <code>required .llsf_msgs.Team team_color = 4;</code>
     * @return Whether the teamColor field is set.
     */
    boolean hasTeamColor();
    /**
     * <pre>
     * Team the robot belongs to
     * </pre>
     *
     * <code>required .llsf_msgs.Team team_color = 4;</code>
     * @return The teamColor.
     */
    org.robocup_logistics.llsf_msgs.TeamProtos.Team getTeamColor();
  }
  /**
   * <pre>
   * Set a robot's maintenance state
   * </pre>
   *
   * Protobuf type {@code llsf_msgs.SetRobotMaintenance}
   */
  public static final class SetRobotMaintenance extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:llsf_msgs.SetRobotMaintenance)
      SetRobotMaintenanceOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SetRobotMaintenance.newBuilder() to construct.
    private SetRobotMaintenance(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SetRobotMaintenance() {
      teamColor_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SetRobotMaintenance();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SetRobotMaintenance(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              robotNumber_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000002;
              maintenance_ = input.readBool();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              org.robocup_logistics.llsf_msgs.TeamProtos.Team value = org.robocup_logistics.llsf_msgs.TeamProtos.Team.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                teamColor_ = rawValue;
              }
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return internal_static_llsf_msgs_SetRobotMaintenance_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return internal_static_llsf_msgs_SetRobotMaintenance_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance.class, org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance.Builder.class);
    }

    /**
     * Protobuf enum {@code llsf_msgs.SetRobotMaintenance.CompType}
     */
    public enum CompType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>COMP_ID = 2000;</code>
       */
      COMP_ID(2000),
      /**
       * <code>MSG_TYPE = 91;</code>
       */
      MSG_TYPE(91),
      ;

      /**
       * <code>COMP_ID = 2000;</code>
       */
      public static final int COMP_ID_VALUE = 2000;
      /**
       * <code>MSG_TYPE = 91;</code>
       */
      public static final int MSG_TYPE_VALUE = 91;


      public final int getNumber() {
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static CompType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static CompType forNumber(int value) {
        switch (value) {
          case 2000: return COMP_ID;
          case 91: return MSG_TYPE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<CompType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          CompType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CompType>() {
              public CompType findValueByNumber(int number) {
                return CompType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance.getDescriptor().getEnumTypes().get(0);
      }

      private static final CompType[] VALUES = values();

      public static CompType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private CompType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:llsf_msgs.SetRobotMaintenance.CompType)
    }

    private int bitField0_;
    public static final int ROBOT_NUMBER_FIELD_NUMBER = 1;
    private int robotNumber_;
    /**
     * <pre>
     * Number of robot to set state
     * </pre>
     *
     * <code>required uint32 robot_number = 1;</code>
     * @return Whether the robotNumber field is set.
     */
    @java.lang.Override
    public boolean hasRobotNumber() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Number of robot to set state
     * </pre>
     *
     * <code>required uint32 robot_number = 1;</code>
     * @return The robotNumber.
     */
    @java.lang.Override
    public int getRobotNumber() {
      return robotNumber_;
    }

    public static final int MAINTENANCE_FIELD_NUMBER = 3;
    private boolean maintenance_;
    /**
     * <pre>
     * True to activate maintenance,
     * false to bring back robot
     * </pre>
     *
     * <code>required bool maintenance = 3;</code>
     * @return Whether the maintenance field is set.
     */
    @java.lang.Override
    public boolean hasMaintenance() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * True to activate maintenance,
     * false to bring back robot
     * </pre>
     *
     * <code>required bool maintenance = 3;</code>
     * @return The maintenance.
     */
    @java.lang.Override
    public boolean getMaintenance() {
      return maintenance_;
    }

    public static final int TEAM_COLOR_FIELD_NUMBER = 4;
    private int teamColor_;
    /**
     * <pre>
     * Team the robot belongs to
     * </pre>
     *
     * <code>required .llsf_msgs.Team team_color = 4;</code>
     * @return Whether the teamColor field is set.
     */
    @java.lang.Override public boolean hasTeamColor() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * Team the robot belongs to
     * </pre>
     *
     * <code>required .llsf_msgs.Team team_color = 4;</code>
     * @return The teamColor.
     */
    @java.lang.Override public org.robocup_logistics.llsf_msgs.TeamProtos.Team getTeamColor() {
      @SuppressWarnings("deprecation")
      org.robocup_logistics.llsf_msgs.TeamProtos.Team result = org.robocup_logistics.llsf_msgs.TeamProtos.Team.valueOf(teamColor_);
      return result == null ? org.robocup_logistics.llsf_msgs.TeamProtos.Team.CYAN : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasRobotNumber()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMaintenance()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTeamColor()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeUInt32(1, robotNumber_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeBool(3, maintenance_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeEnum(4, teamColor_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, robotNumber_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, maintenance_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, teamColor_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance)) {
        return super.equals(obj);
      }
      org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance other = (org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance) obj;

      if (hasRobotNumber() != other.hasRobotNumber()) return false;
      if (hasRobotNumber()) {
        if (getRobotNumber()
            != other.getRobotNumber()) return false;
      }
      if (hasMaintenance() != other.hasMaintenance()) return false;
      if (hasMaintenance()) {
        if (getMaintenance()
            != other.getMaintenance()) return false;
      }
      if (hasTeamColor() != other.hasTeamColor()) return false;
      if (hasTeamColor()) {
        if (teamColor_ != other.teamColor_) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRobotNumber()) {
        hash = (37 * hash) + ROBOT_NUMBER_FIELD_NUMBER;
        hash = (53 * hash) + getRobotNumber();
      }
      if (hasMaintenance()) {
        hash = (37 * hash) + MAINTENANCE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getMaintenance());
      }
      if (hasTeamColor()) {
        hash = (37 * hash) + TEAM_COLOR_FIELD_NUMBER;
        hash = (53 * hash) + teamColor_;
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Set a robot's maintenance state
     * </pre>
     *
     * Protobuf type {@code llsf_msgs.SetRobotMaintenance}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:llsf_msgs.SetRobotMaintenance)
        org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenanceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return internal_static_llsf_msgs_SetRobotMaintenance_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return internal_static_llsf_msgs_SetRobotMaintenance_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance.class, org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance.Builder.class);
      }

      // Construct using org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        robotNumber_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        maintenance_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        teamColor_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return internal_static_llsf_msgs_SetRobotMaintenance_descriptor;
      }

      @java.lang.Override
      public org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance getDefaultInstanceForType() {
        return getDefaultInstance();
      }

      @java.lang.Override
      public org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance build() {
        org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance buildPartial() {
        org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance result = new org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.robotNumber_ = robotNumber_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.maintenance_ = maintenance_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.teamColor_ = teamColor_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance) {
          return mergeFrom((org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance other) {
        if (other == getDefaultInstance()) return this;
        if (other.hasRobotNumber()) {
          setRobotNumber(other.getRobotNumber());
        }
        if (other.hasMaintenance()) {
          setMaintenance(other.getMaintenance());
        }
        if (other.hasTeamColor()) {
          setTeamColor(other.getTeamColor());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasRobotNumber()) {
          return false;
        }
        if (!hasMaintenance()) {
          return false;
        }
        if (!hasTeamColor()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int robotNumber_ ;
      /**
       * <pre>
       * Number of robot to set state
       * </pre>
       *
       * <code>required uint32 robot_number = 1;</code>
       * @return Whether the robotNumber field is set.
       */
      @java.lang.Override
      public boolean hasRobotNumber() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * Number of robot to set state
       * </pre>
       *
       * <code>required uint32 robot_number = 1;</code>
       * @return The robotNumber.
       */
      @java.lang.Override
      public int getRobotNumber() {
        return robotNumber_;
      }
      /**
       * <pre>
       * Number of robot to set state
       * </pre>
       *
       * <code>required uint32 robot_number = 1;</code>
       * @param value The robotNumber to set.
       * @return This builder for chaining.
       */
      public Builder setRobotNumber(int value) {
        bitField0_ |= 0x00000001;
        robotNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Number of robot to set state
       * </pre>
       *
       * <code>required uint32 robot_number = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRobotNumber() {
        bitField0_ = (bitField0_ & ~0x00000001);
        robotNumber_ = 0;
        onChanged();
        return this;
      }

      private boolean maintenance_ ;
      /**
       * <pre>
       * True to activate maintenance,
       * false to bring back robot
       * </pre>
       *
       * <code>required bool maintenance = 3;</code>
       * @return Whether the maintenance field is set.
       */
      @java.lang.Override
      public boolean hasMaintenance() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * True to activate maintenance,
       * false to bring back robot
       * </pre>
       *
       * <code>required bool maintenance = 3;</code>
       * @return The maintenance.
       */
      @java.lang.Override
      public boolean getMaintenance() {
        return maintenance_;
      }
      /**
       * <pre>
       * True to activate maintenance,
       * false to bring back robot
       * </pre>
       *
       * <code>required bool maintenance = 3;</code>
       * @param value The maintenance to set.
       * @return This builder for chaining.
       */
      public Builder setMaintenance(boolean value) {
        bitField0_ |= 0x00000002;
        maintenance_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * True to activate maintenance,
       * false to bring back robot
       * </pre>
       *
       * <code>required bool maintenance = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMaintenance() {
        bitField0_ = (bitField0_ & ~0x00000002);
        maintenance_ = false;
        onChanged();
        return this;
      }

      private int teamColor_ = 0;
      /**
       * <pre>
       * Team the robot belongs to
       * </pre>
       *
       * <code>required .llsf_msgs.Team team_color = 4;</code>
       * @return Whether the teamColor field is set.
       */
      @java.lang.Override public boolean hasTeamColor() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       * Team the robot belongs to
       * </pre>
       *
       * <code>required .llsf_msgs.Team team_color = 4;</code>
       * @return The teamColor.
       */
      @java.lang.Override
      public org.robocup_logistics.llsf_msgs.TeamProtos.Team getTeamColor() {
        @SuppressWarnings("deprecation")
        org.robocup_logistics.llsf_msgs.TeamProtos.Team result = org.robocup_logistics.llsf_msgs.TeamProtos.Team.valueOf(teamColor_);
        return result == null ? org.robocup_logistics.llsf_msgs.TeamProtos.Team.CYAN : result;
      }
      /**
       * <pre>
       * Team the robot belongs to
       * </pre>
       *
       * <code>required .llsf_msgs.Team team_color = 4;</code>
       * @param value The teamColor to set.
       * @return This builder for chaining.
       */
      public Builder setTeamColor(org.robocup_logistics.llsf_msgs.TeamProtos.Team value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        teamColor_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Team the robot belongs to
       * </pre>
       *
       * <code>required .llsf_msgs.Team team_color = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearTeamColor() {
        bitField0_ = (bitField0_ & ~0x00000004);
        teamColor_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:llsf_msgs.SetRobotMaintenance)
    }

    // @@protoc_insertion_point(class_scope:llsf_msgs.SetRobotMaintenance)
    private static final org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance();
    }

    public static org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<SetRobotMaintenance>
        PARSER = new com.google.protobuf.AbstractParser<SetRobotMaintenance>() {
      @java.lang.Override
      public SetRobotMaintenance parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SetRobotMaintenance(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SetRobotMaintenance> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SetRobotMaintenance> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_llsf_msgs_SetRobotMaintenance_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_llsf_msgs_SetRobotMaintenance_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023RobotCommands.proto\022\tllsf_msgs\032\nTeam.p" +
      "roto\"\215\001\n\023SetRobotMaintenance\022\024\n\014robot_nu" +
      "mber\030\001 \002(\r\022\023\n\013maintenance\030\003 \002(\010\022#\n\nteam_" +
      "color\030\004 \002(\0162\017.llsf_msgs.Team\"&\n\010CompType" +
      "\022\014\n\007COMP_ID\020\320\017\022\014\n\010MSG_TYPE\020[B6\n\037org.robo" +
      "cup_logistics.llsf_msgsB\023RobotCommandsPr" +
      "otos"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.robocup_logistics.llsf_msgs.TeamProtos.getDescriptor(),
        });
    internal_static_llsf_msgs_SetRobotMaintenance_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_llsf_msgs_SetRobotMaintenance_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_llsf_msgs_SetRobotMaintenance_descriptor,
        new java.lang.String[] { "RobotNumber", "Maintenance", "TeamColor", });
    org.robocup_logistics.llsf_msgs.TeamProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
