// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MachineDescription.proto

package org.robocup_logistics.llsf_msgs;

public final class MachineDescriptionProtos {
  private MachineDescriptionProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code llsf_msgs.LightColor}
   */
  public enum LightColor
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>RED = 0;</code>
     */
    RED(0),
    /**
     * <code>YELLOW = 1;</code>
     */
    YELLOW(1),
    /**
     * <code>GREEN = 2;</code>
     */
    GREEN(2),
    ;

    /**
     * <code>RED = 0;</code>
     */
    public static final int RED_VALUE = 0;
    /**
     * <code>YELLOW = 1;</code>
     */
    public static final int YELLOW_VALUE = 1;
    /**
     * <code>GREEN = 2;</code>
     */
    public static final int GREEN_VALUE = 2;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static LightColor valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static LightColor forNumber(int value) {
      switch (value) {
        case 0: return RED;
        case 1: return YELLOW;
        case 2: return GREEN;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<LightColor>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        LightColor> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<LightColor>() {
            public LightColor findValueByNumber(int number) {
              return LightColor.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.robocup_logistics.llsf_msgs.MachineDescriptionProtos.getDescriptor().getEnumTypes().get(0);
    }

    private static final LightColor[] VALUES = values();

    public static LightColor valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private LightColor(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:llsf_msgs.LightColor)
  }

  /**
   * Protobuf enum {@code llsf_msgs.LightState}
   */
  public enum LightState
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>OFF = 0;</code>
     */
    OFF(0),
    /**
     * <code>ON = 1;</code>
     */
    ON(1),
    /**
     * <code>BLINK = 2;</code>
     */
    BLINK(2),
    ;

    /**
     * <code>OFF = 0;</code>
     */
    public static final int OFF_VALUE = 0;
    /**
     * <code>ON = 1;</code>
     */
    public static final int ON_VALUE = 1;
    /**
     * <code>BLINK = 2;</code>
     */
    public static final int BLINK_VALUE = 2;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static LightState valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static LightState forNumber(int value) {
      switch (value) {
        case 0: return OFF;
        case 1: return ON;
        case 2: return BLINK;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<LightState>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        LightState> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<LightState>() {
            public LightState findValueByNumber(int number) {
              return LightState.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.robocup_logistics.llsf_msgs.MachineDescriptionProtos.getDescriptor().getEnumTypes().get(1);
    }

    private static final LightState[] VALUES = values();

    public static LightState valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private LightState(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:llsf_msgs.LightState)
  }

  /**
   * Protobuf enum {@code llsf_msgs.SSOp}
   */
  public enum SSOp
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>STORE = 1;</code>
     */
    STORE(1),
    /**
     * <code>RETRIEVE = 2;</code>
     */
    RETRIEVE(2),
    /**
     * <code>CHANGE_INFO = 3;</code>
     */
    CHANGE_INFO(3),
    ;

    /**
     * <code>STORE = 1;</code>
     */
    public static final int STORE_VALUE = 1;
    /**
     * <code>RETRIEVE = 2;</code>
     */
    public static final int RETRIEVE_VALUE = 2;
    /**
     * <code>CHANGE_INFO = 3;</code>
     */
    public static final int CHANGE_INFO_VALUE = 3;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static SSOp valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static SSOp forNumber(int value) {
      switch (value) {
        case 1: return STORE;
        case 2: return RETRIEVE;
        case 3: return CHANGE_INFO;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<SSOp>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        SSOp> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<SSOp>() {
            public SSOp findValueByNumber(int number) {
              return SSOp.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.robocup_logistics.llsf_msgs.MachineDescriptionProtos.getDescriptor().getEnumTypes().get(2);
    }

    private static final SSOp[] VALUES = values();

    public static SSOp valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private SSOp(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:llsf_msgs.SSOp)
  }

  /**
   * Protobuf enum {@code llsf_msgs.CSOp}
   */
  public enum CSOp
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>RETRIEVE_CAP = 1;</code>
     */
    RETRIEVE_CAP(1),
    /**
     * <code>MOUNT_CAP = 2;</code>
     */
    MOUNT_CAP(2),
    ;

    /**
     * <code>RETRIEVE_CAP = 1;</code>
     */
    public static final int RETRIEVE_CAP_VALUE = 1;
    /**
     * <code>MOUNT_CAP = 2;</code>
     */
    public static final int MOUNT_CAP_VALUE = 2;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static CSOp valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static CSOp forNumber(int value) {
      switch (value) {
        case 1: return RETRIEVE_CAP;
        case 2: return MOUNT_CAP;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CSOp>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        CSOp> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CSOp>() {
            public CSOp findValueByNumber(int number) {
              return CSOp.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.robocup_logistics.llsf_msgs.MachineDescriptionProtos.getDescriptor().getEnumTypes().get(3);
    }

    private static final CSOp[] VALUES = values();

    public static CSOp valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private CSOp(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:llsf_msgs.CSOp)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030MachineDescription.proto\022\tllsf_msgs*,\n" +
      "\nLightColor\022\007\n\003RED\020\000\022\n\n\006YELLOW\020\001\022\t\n\005GREE" +
      "N\020\002*(\n\nLightState\022\007\n\003OFF\020\000\022\006\n\002ON\020\001\022\t\n\005BL" +
      "INK\020\002*0\n\004SSOp\022\t\n\005STORE\020\001\022\014\n\010RETRIEVE\020\002\022\017" +
      "\n\013CHANGE_INFO\020\003*\'\n\004CSOp\022\020\n\014RETRIEVE_CAP\020" +
      "\001\022\r\n\tMOUNT_CAP\020\002B;\n\037org.robocup_logistic" +
      "s.llsf_msgsB\030MachineDescriptionProtos"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
